/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public int getSum(int a, int b){
        // Infinte loop
        for(int i=0; i<100; i--){
            a=a+b;
        }
        return a+b;
    }
    
    public int getSub(int a, int b){
        // Infinte loop
        for(int i=0; i<100; i--){
            a=a+b;
        }
        return a-b;
    }


    public void chooseNumber(int num){
        // using Switch Statement instead of If else
        switch (num) {
            case 0:
                System.out.println("Bad luck");
                
                // not using break
            case 1:
                System.out.println("Congratulations");;

            case 2:
                System.out.println("Hello");
                
            // No default statement 
        }
    }

    public String getGreeting() {
        // "StringBuilder" and "StringBuffer" should not be instantiated with a character and unused variable
        StringBuilder sb = new StringBuilder('x');
        return "Hello World!";
        // Unusual comments
        // int i = 10;
        // int j = 20;
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
    }
}
